### ISSUE TITLE
Запуск ossh с запросом пароля

### ISSUE THREAD

**Issue by elchako** [kt97679/one-ssh#11]
Добрый день! пытаюсь запустить ossh.py с запросом пароля, но в ответ получаю от всех машин [Errno 104] Connection reset by peer

python3 ossh.py -H "10.10.10.12 10.10.10.11" -l user -c 'uptime' -A

ssh user@10.10.10.12 пускает

OSSH автоматически принимает ключ? может в этом проблема? или может я не включил какую-то опцию?

Воспользоваться входом по ключу нет возможности, только через пароль.

Спасибо!

**Comment by kt97679** [comment]
Здравствуйте. К сожалению python версия это эксперимент, который так и не был доведен до ума. В настоящий момент основной является версия на go. Если для вас не критично использовать именно python можно попросить вас попробовать go-версию?

**Comment by elchako** [comment]
Сейчас попробовал на другой серии Linux машин на Ubuntu и Gentoo, все работает
Получается не работает только на TinyCore Linux
К сожалению GO не знаю совсем, даже не знаю с какой стороны к нему подойти )

**Comment by kt97679** [comment]
Ух, TinyCore насколько я знаю достаточно экзотическая система, так что на ней безусловно могут наблюдаться всякие чудеса. go не так страшен, в readme есть инструкция по сборке. Если у вас что-то не заработает - пишите, буду рад помочь.

**Comment by kt97679** [comment]
Я добавил билд бинарников, вы можете найти их в релизах. Возможно эти бинарники будут нормально работать на TinyCore?
