### ISSUE TITLE
Вывод данных ossh

### ISSUE THREAD

**Issue by elchako** [kt97679/one-ssh#12]
Добрый вечер! Во первых большое спасибо за ossh, очень быстро работает. У меня есть пару вопросов.
Мжно ли убрать из вывода ошибки? Использую Python версию. Использую аргументы -P -i
ipaddress [2] Timeout: No Response from Host.
ipaddress [1] 
ipaddress [2] Timeout: No Response from Host.
ipaddress [1] 

И можно ли убрать из вывода [1] [2] или нужно править исходный код ?

Благодарю!

**Comment by kt97679** [comment]
Здравствуйте. Обычно если мне надо отфильтровать из вывод ошибки я просто использую `grep` вот так:
```
$ echo -e 'hostname [1] some message\nhostname [2] some error'|grep -v '\[2\]'
hostname [1] some message
$ 
```
Если вы хотите убрать именно [1] и [2], то это можно сделат так:
```
$ echo -e 'hostname [1] some message\nhostname [2] some error'|sed -e 's/^\([^ ]*\)  *\[.\]/\1/'
hostname some message
hostname some error
$ 
```

**Comment by elchako** [comment]
Спасибо! Буду грепать )
