### ISSUE TITLE
Suggestion: Allow '#' (or other comment characters) in hosts files

### ISSUE THREAD

**Issue by deoren** [kt97679/one-ssh#2]
Example file:

```
# Red Hat Servers
host1.example.com

# Ubuntu Servers
host2.example.com

# Down for maintenance
# host3.example.com
# host4.example.com

```

Not a required feature for use, but it could use useful if nothing else for temporarily commenting out a host in one or more files.

**Comment by kt97679** [comment]
Hi @deoren , thank you very much for suggestion. I just added support for # style comments, please see if this works for you. While this can be used to manage subset of machines where you want to run commands I highly recommend to implement OSSHInventory class that will allow you to do custom filtering.

**Comment by deoren** [comment]
> @kt97679: Hi @deoren , thank you very much for suggestion. I just added support for # style comments, please see if this works for you.

Thanks! The change works as advertised. :)

> @kt97679: While this can be used to manage subset of machines where you want to run commands I highly recommend to implement OSSHInventory class that will allow you to do custom filtering.

Thanks for the tip. I don't have Ruby experience, but what you've created thus far in the form of the `bin/ossh` script works well for my needs right now.
